### ISSUE TITLE
Lineage 17.1 kernel 4.9 compilation issue 

### ISSUE THREAD

**Issue by kondors1995** [zeelog/android_kernel_xiaomi_mido#3]
PATH tool "bison" used: []string{"bison", "-d", "--output=scripts/dtc-aosp/dtc/dtc-parser.tab.c", "--defines=scripts/dtc-aosp/dtc/dtc-parser.h", "-Wno-conflicts-sr", "/datadrive/los/kernel/xiaomi/mido/scripts/dtc-aosp/dtc/dtc-parser.y"}

How did you compiled 4.9 kernel in lineage 17,1?

From my tests its fails to compile

**Comment by zeelog** [comment]
just pick this https://github.com/KudProject/kernel_xiaomi_msm8953-4.9/commit/ee7cfc088597eb9b13b378209bb52ea0296b3bb0
credit to KrasCGQ.

**Comment by kondors1995** [comment]
tnx will try
